### DISCUSSION TITLE
docker-compose for solidinvoice

### DISCUSSION THREAD

**Discussion by DimebagCFH** [SolidInvoice/SolidInvoice#983] [Q&A] [answered]
Dears,
I'm using this docker compose for solidinvoice 
It seems not working, when it's installed, arriving at the database config page
I don't know which host I have to define (to fill)

version: '3.9'
services:
  db:
    image: mysql:5.7
    volumes:
      - /volume1/docker/solidinvoicedb:/var/lib/mysql:rw
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    environment:
      MYSQL_DATABASE: solidinvoice
      MYSQL_ROOT_PASSWORD: rootpasword
      MYSQL_USER: solidinvoice
      MYSQL_PASSWORD: userpassword
  app:
    image: solidinvoice/solidinvoice
    depends_on:
      - db
    ports:
      - 5484:80
    restart: on-failure:5

I'm using that tuto
https://mariushosting.com/how-to-install-solidinvoice-on-your-synology-nas/

Thanks in advance for your help

**Comment by vahidirp** [comment, marked as answer]
```
version: '3'

services:
  solidinvoice:
    image: solidinvoice/solidinvoice:latest
    ports:
      - "8080:80"
    environment:
      - DATABASE_URL=mysql://solidinvoice:solidinvoice@mysql/solidinvoice
      - MAILER_URL=smtp://mailcatcher:1025
    depends_on:
      - mysql
      - mailcatcher
    networks:
      - solidinvoice-network

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=solidinvoice
      - MYSQL_USER=solidinvoice
      - MYSQL_PASSWORD=solidinvoice
    networks:
      - solidinvoice-network

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
    networks:
      - solidinvoice-network

networks:
  solidinvoice-network:
```
