### ISSUE TITLE
Deploying with portainer: SQLSTATE[HY000] [1130] Host is not allowed to connect to this MySQL server

### ISSUE THREAD

**Issue by Tiritibambix** [SolidInvoice/SolidInvoice#1069]
**Describe the bug**
Database won't be created

**To Reproduce**
Following instructions, I built this docker-compose to deploy it as a stack in portainer:
```
version: '3.7'

services:
   solidinvoice:
    image: solidinvoice/solidinvoice
    ports:
      - "8000:80"
    volumes:
      - /path/to/data:/var/www/html/var/data
      - /path/to/logs:/var/www/html/var/logs
      - /path/to/uploads:/var/www/html/web/uploads
    restart: unless-stopped
    depends_on:
      - db

   db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: solidinvoice
      MYSQL_USER: solidinvoice
      MYSQL_PASSWORD: password
    volumes:
      - /path/to/db_data:/var/lib/mysql
    restart: unless-stopped
```
Stack deploys and db container is named `solidinvoice-db-1`
I go to the Database Config page en fill the fields as follow:
```
Driver: Mysql
Host: solidinvoice-db-1
Port: 3306
User: solidinvoice
Password: password
Database Name: solidinvoice
```
I then get this error message: ` Error An exception occurred in the driver: SQLSTATE[HY000] [1130] Host '172.21.0.3' is not allowed to connect to this MySQL server `

![Host is not allowed to connect to this MySQL server](https://clip.steph.click/-P36AhVbzzi/solidinvoice.JPG)

**Desktop (please complete the following information):**
```
Operating System: Debian GNU/Linux 12 (bookworm)
Kernel: Linux 6.1.0-20-amd64
Architecture: x86-64
```
```
Client: Docker Engine - Community
 Version:           26.1.0
 API version:       1.45
 Go version:        go1.21.9
 Git commit:        9714adc
 Built:             Mon Apr 22 17:06:56 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.0
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.9
  Git commit:       c8af8eb
  Built:            Mon Apr 22 17:06:56 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.31
```
```
Docker Compose version v2.26.1
```
```
Portainer Business Edition 2.19.5
```

Any help would be greatly appreciated.

**Comment by dennysubke** [comment]
Same Problem...

**Comment by pierredup** [comment]
It sounds like it may be a permission issue on MySQL. Can you try running the below commands to allow connections to the MySQL server?

Log into the MySQL container

``` bash
docker exec -it solidinvoice-db-1 mysql -u root -p
```

Add permission to allow connections to the solidinvoice database

```mysql
GRANT ALL PRIVILEGES ON solidinvoice.* TO 'solidinvoice'@'%' IDENTIFIED BY 'password';
FLUSH PRIVILEGES;
```

**Comment by pierredup** [comment]
If the issue persists, please feel free to re-open this

**Comment by mariushosting** [comment]
> If the issue persists, please feel free to re-open this

which is the default port on the latest version :80 or :8765?

**Comment by pierredup** [comment]
The default port on 2.3+ is `8765`.

**Comment by mariushosting** [comment]
> The default port on 2.3+ is `8765`.

I get a totally blank white page with fresh installation using the latest version.

```
services:
  db:
    image: mysql:5.7
    container_name: Solidinvoice-DB
    volumes:
      - /volume1/docker/solidinvoice/db:/var/lib/mysql:rw
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    environment:
      MYSQL_DATABASE: solidinvoice
      MYSQL_ROOT_PASSWORD: mariushosting
      MYSQL_USER: solidinvoice
      MYSQL_PASSWORD: mariushosting
      
  solidinvoice:
    image: solidinvoice/solidinvoice:2.3.2
    container_name: Solidinvoice
    depends_on:
      - db
    volumes:
      - /volume1/docker/solidinvoice/data:/var/www/html/var/data:rw
      - /volume1/docker/solidinvoice/logs:/var/www/html/var/logs:rw
      - /volume1/docker/solidinvoice/uploads:/var/www/html/web/uploads:rw
    ports:
      - 5484:8765
    restart: on-failure:5
```
