### ISSUE TITLE
Docker volume mapping, Standard works, Full does not

### ISSUE THREAD

**Issue by davi2td** [SolidInvoice/SolidInvoice#882]
**Describe the bug**
When trying to use volume mapping:
**Standard** works, see compose example below
**Full**, mysql files not copied, auto.cnf & binlog.index are created only, see compose example below
**To Reproduce**
Working Standard Compose:
```
version: "3.3"

services:
  db:
    image: "mysql:8"
    volumes:
      - /c/docker-stuff/solidinvoice-standard/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: solidinvoice
      MYSQL_ROOT_PASSWORD: "your_super_complex_password_here"
      MYSQL_USER: "solidinvoice"
      MYSQL_PASSWORD: "your_super_complex_different_password_here"
  app:
    image: solidinvoice/solidinvoice:latest
    depends_on:
      - db
    ports:
      - "8234:80"
    restart: always
```
Not working Full Compose:
```
version: "3.3"

services:
  app:
    image: solidinvoice/solidinvoice:latest-full
    volumes:
      - /c/docker-stuff/solidinvoice-full/db_data:/var/lib/mysql      
    restart: always      
    ports:
      - "8235:80"
```
Also receive the error in browser : 
```
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
```
Obviously since mysql files missing ...
Also no errors in logs for running container ...
**Expected behavior**
Docker Full, mysql data copied to mounted volume and copies files as in Standard
